# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30eb05b6a746d160dccbf8f3a61d22b5a9e81ab5131deb5fc92397deffe58638777ff87f45fa97e65cc3e1e5c691e4a50fbeac63debe02f91f5fb9f3f54adf79

test:
  secret_key_base: 392fac3da0d984fb4fc4abdd517aa2141f57101f02fea4417108e07de331391dc77f94367d3a3412884a9b708db9a6d38a53fe37030b40a5b6ab432e0feff675

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
